export type TechnologyType =
    | "Amplify"
    | "Angular"
    | "APM"
    | "App"
    | "AWS EC2"
    | "AWS ECS"
    | "AWS Lambda"
    | "CI/CD"
    | "CMS"
    | "Data analysis"
    | "Design Thinking"
    | "Docker"
    | "Figma"
    | "GitHub Actions"
    | "Jenkins"
    | "Infra"
    | "Kubernetes"
    | "Next.js"
    | "Node.js (Express)"
    | "Node.js (Nest)"
    | "PostgreSQL"
    | "Python"
    | "Pandas"
    | "RabbitMQ"
    | "React"
    | "React Native"
    | "SonarQube"
    | "Serverless"
    | "Tailwind"
    | "Typescript"
    | "Treinamentos"
    | "Training"
    | "Web"
    | ".Net Core";
